export const CONTAINERUS_THEME: any = {
  base: 'vs-dark',
  inherit: true,
  rules: [
    { token: 'comment', foreground: '6A9955', fontStyle: 'italic' },
    { token: 'keyword', foreground: 'C586C0' },
    { token: 'string', foreground: 'CE9178' },
    { token: 'number', foreground: 'B5CEA8' },
    { token: 'type', foreground: '4EC9B0' },
    { token: 'function', foreground: 'DCDCAA' },
    { token: 'variable', foreground: '9CDCFE' },
    { token: 'constant', foreground: '4FC1FF' },
    { token: 'tag', foreground: '569CD6' },
    { token: 'attribute.name', foreground: '9CDCFE' },
    { token: 'attribute.value', foreground: 'CE9178' },
    { token: 'type.yaml', foreground: '569CD6' },
    { token: 'string.yaml', foreground: 'CE9178' },
    { token: 'number.yaml', foreground: 'B5CEA8' },
    { token: 'keyword.yaml', foreground: '569CD6' },
  ],
  colors: {
    'editor.background': '#09090b',
    'editor.foreground': '#d4d4d8',
    'editor.lineHighlightBackground': '#18181b',
    'editorCursor.foreground': '#d4d4d8',
    'editor.selectionBackground': '#3f3f4680',
    'editorLineNumber.foreground': '#52525b',
    'editorLineNumber.activeForeground': '#a1a1aa',
    'editorWidget.background': '#18181b',
    'editorWidget.border': '#27272a',
    'input.background': '#27272a',
    'input.border': '#3f3f46',
    'dropdown.background': '#18181b',
    'dropdown.border': '#3f3f46',
    'list.hoverBackground': '#27272a',
    'list.activeSelectionBackground': '#3f3f46',
    'editorGutter.background': '#09090b',
    'scrollbar.shadow': '#00000000',
    'scrollbarSlider.background': '#52525b80',
    'scrollbarSlider.hoverBackground': '#71717a80',
    'scrollbarSlider.activeBackground': '#a1a1aa80',
  },
};
