import './__testing__/webcrypto-polyfill';
import { describe, it, expect } from 'vitest';

import { containerAclResourceId } from './container-acl-id';

// Byte-identity with the Rust `container_acl_resource_id()` helper in
// crates/containerus-server/src/auth/middleware.rs is the whole point — the
// UI write path and the middleware read path MUST produce the same UUID or
// container ACLs silently miss at enforcement time. These fixtures were
// generated by running the Rust helper against identical inputs.
describe('containerAclResourceId', () => {
  it('matches the Rust middleware for a stable (system, runtime) pair', async () => {
    const id = await containerAclResourceId(
      '11111111-2222-3333-4444-555555555555',
      'abc123def456',
    );
    expect(id).toBe('c40d9fd2-2c80-556d-99b7-5c1ace1bfd16');
  });

  it('namespaces by system — same runtime id under two systems never collides', async () => {
    const a = await containerAclResourceId(
      '11111111-2222-3333-4444-555555555555',
      'runtime-xyz',
    );
    const b = await containerAclResourceId(
      '99999999-8888-7777-6666-555555555555',
      'runtime-xyz',
    );
    expect(a).not.toBe(b);
  });

  it('is deterministic across calls', async () => {
    const sys = '11111111-2222-3333-4444-555555555555';
    const a = await containerAclResourceId(sys, 'ct1');
    const b = await containerAclResourceId(sys, 'ct1');
    expect(a).toBe(b);
  });

  it('rejects a malformed system UUID', async () => {
    await expect(
      containerAclResourceId('not-a-uuid', 'ct1'),
    ).rejects.toThrow(/Invalid UUID/);
  });
});
